import type { Metadata } from "next";
import { SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `The terms for using ${SITE_NAME}'s free calculators and document generators.`,
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-14">
      <p className="font-sans text-xs font-bold uppercase tracking-widest text-moss">
        Legal
      </p>
      <h1 className="mt-2 font-serif text-4xl font-bold">Terms of Service</h1>
      <p className="mt-2 font-sans text-sm text-ink/50">
        Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </p>

      <div className="mt-8 space-y-6 font-sans text-sm leading-relaxed text-ink/80">
        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Not legal advice
          </h2>
          <p className="mt-2">
            {SITE_NAME} provides self-help calculators, document templates,
            and general summaries of publicly available landlord-tenant law.
            Nothing on this site is legal advice, and using it does not
            create an attorney-client relationship. Landlord-tenant law
            varies by state and by city, changes over time, and can depend
            on facts specific to your situation. For anything contested or
            high-stakes, consult a licensed attorney in your jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Accuracy of state law summaries
          </h2>
          <p className="mt-2">
            The state-by-state pages summarize general statutory rules
            (deposit caps, refund deadlines, interest requirements, and
            penalties) as of the date they were last reviewed. They do not
            cover every local ordinance, may not reflect the most recent
            legislative changes, and are provided &quot;as is&quot; without
            warranty of accuracy or completeness. Always verify current
            requirements against your state&apos;s official statute before
            relying on them.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Generated documents
          </h2>
          <p className="mt-2">
            PDF statements and letters generated by this site are templates
            based on information you provide. You are responsible for
            reviewing the final document for accuracy and for complying with
            any notice, delivery, or formatting requirements that apply in
            your jurisdiction before sending it to a tenant.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            No warranty; limitation of liability
          </h2>
          <p className="mt-2">
            This site is provided free of charge, &quot;as is&quot; and
            &quot;as available,&quot; without warranties of any kind. To the
            fullest extent permitted by law, {SITE_NAME} and its operators
            are not liable for any damages arising from your use of the
            calculators, templates, or state law summaries, including
            damages resulting from errors, omissions, or reliance on
            outdated information.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Acceptable use
          </h2>
          <p className="mt-2">
            Please don&apos;t scrape, republish, or resell the state law
            content in bulk, or attempt to disrupt the site&apos;s normal
            operation. Reasonable personal and business use of the
            calculators and generators is welcome and encouraged.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">Changes</h2>
          <p className="mt-2">
            We may update these terms as the site changes. Continued use
            after an update means you accept the revised terms.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">Contact</h2>
          <p className="mt-2">
            Questions about these terms can be sent to{" "}
            <a href="mailto:hello@landlordtools.io" className="underline hover:text-moss">
              hello@landlordtools.io
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
