export type StateLaw = {
  slug: string;
  name: string;
  abbr: string;
  depositCap: string;
  returnDeadlineDays: number;
  returnDeadlineNote?: string;
  interestRequired: boolean;
  interestNote: string;
  separateAccountRequired: boolean;
  penalty: string;
  statute: string;
};

export const statesData: StateLaw[] = [
  {
    slug: "alabama",
    name: "Alabama",
    abbr: "AL",
    depositCap: "1 month's rent",
    returnDeadlineDays: 35,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Willful violation can allow the tenant to recover the deposit plus damages.",
    statute: "Ala. Code § 35-9A-201",
  },
  {
    slug: "alaska",
    name: "Alaska",
    abbr: "AK",
    depositCap: "2 months' rent (1 month if lease term is 6+ months, after first 6 months)",
    returnDeadlineDays: 14,
    returnDeadlineNote: "14 days if no deductions claimed, 30 days if deductions are itemized.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Tenant may recover double the wrongfully withheld amount.",
    statute: "Alaska Stat. § 34.03.070",
  },
  {
    slug: "arizona",
    name: "Arizona",
    abbr: "AZ",
    depositCap: "1.5 months' rent",
    returnDeadlineDays: 14,
    returnDeadlineNote: "14 business days after move-out.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Tenant may recover up to twice the amount wrongfully withheld.",
    statute: "Ariz. Rev. Stat. § 33-1321",
  },
  {
    slug: "arkansas",
    name: "Arkansas",
    abbr: "AR",
    depositCap: "2 months' rent",
    returnDeadlineDays: 60,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Willful noncompliance can expose the landlord to actual damages plus statutory penalties.",
    statute: "Ark. Code § 18-16-305",
  },
  {
    slug: "california",
    name: "California",
    abbr: "CA",
    depositCap: "1 month's rent (2 months for landlords who own no more than 2 residential units, and unless certain shared-housing rules apply)",
    returnDeadlineDays: 21,
    interestRequired: false,
    interestNote: "No statewide requirement, but some cities (e.g., San Francisco) mandate annual interest on deposits.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can expose the landlord to up to twice the deposit in damages.",
    statute: "Cal. Civ. Code § 1950.5",
  },
  {
    slug: "colorado",
    name: "Colorado",
    abbr: "CO",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    returnDeadlineNote: "Up to 60 days if the lease specifies a longer period.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Willful failure to return can trigger treble damages plus reasonable attorney's fees.",
    statute: "Colo. Rev. Stat. § 38-12-103",
  },
  {
    slug: "connecticut",
    name: "Connecticut",
    abbr: "CT",
    depositCap: "2 months' rent (1 month if tenant is 62 or older)",
    returnDeadlineDays: 30,
    returnDeadlineNote: "30 days, or 15 days after receiving tenant's forwarding address, whichever is later.",
    interestRequired: true,
    interestNote: "Annual interest at a rate set by the state banking commissioner is required.",
    separateAccountRequired: false,
    penalty: "Wrongful withholding can result in twice the amount owed.",
    statute: "Conn. Gen. Stat. § 47a-21",
  },
  {
    slug: "delaware",
    name: "Delaware",
    abbr: "DE",
    depositCap: "1 month's rent (no cap for leases under 1 year in some cases)",
    returnDeadlineDays: 20,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    penalty: "Noncompliance can result in double damages.",
    statute: "Del. Code tit. 25, § 5514",
  },
  {
    slug: "district-of-columbia",
    name: "District of Columbia",
    abbr: "DC",
    depositCap: "1 month's rent",
    returnDeadlineDays: 45,
    interestRequired: true,
    interestNote: "Interest at the passbook savings rate is required for the deposit period.",
    separateAccountRequired: false,
    penalty: "Improper withholding can lead to treble damages.",
    statute: "D.C. Code § 42-3502.17",
  },
  {
    slug: "florida",
    name: "Florida",
    abbr: "FL",
    depositCap: "No statutory cap",
    returnDeadlineDays: 15,
    returnDeadlineNote: "15 days if no deductions; 30 days if the landlord intends to make deductions (with written notice).",
    interestRequired: false,
    interestNote: "Interest is only required if the lease or local ordinance requires it.",
    separateAccountRequired: false,
    penalty: "Failure to follow notice procedures forfeits the landlord's right to keep any part of the deposit.",
    statute: "Fla. Stat. § 83.49",
  },
  {
    slug: "georgia",
    name: "Georgia",
    abbr: "GA",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    returnDeadlineNote: "Applies to landlords with 10+ units, who must escrow deposits.",
    penalty: "Failure to provide an itemized list can forfeit the right to withhold for damages.",
    statute: "Ga. Code § 44-7-30",
  },
  {
    slug: "hawaii",
    name: "Hawaii",
    abbr: "HI",
    depositCap: "1 month's rent",
    returnDeadlineDays: 14,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in damages up to the amount wrongfully withheld.",
    statute: "Haw. Rev. Stat. § 521-44",
  },
  {
    slug: "idaho",
    name: "Idaho",
    abbr: "ID",
    depositCap: "No statutory cap",
    returnDeadlineDays: 21,
    returnDeadlineNote: "21 days, or 30 days if the lease specifies a longer period.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith withholding can result in damages up to twice the amount withheld.",
    statute: "Idaho Code § 6-321",
  },
  {
    slug: "illinois",
    name: "Illinois",
    abbr: "IL",
    depositCap: "No statewide cap (Chicago limits vary by ordinance)",
    returnDeadlineDays: 45,
    returnDeadlineNote: "30 days for an itemized statement, 45 days to refund the balance (varies for buildings of 5+ units).",
    interestRequired: false,
    interestNote: "Interest is required only for landlords with 25+ units in the same building (or Chicago's separate ordinance).",
    separateAccountRequired: false,
    penalty: "Willful noncompliance for buildings of 5+ units can result in 2x damages plus attorney's fees.",
    statute: "765 ILCS 710/1",
  },
  {
    slug: "indiana",
    name: "Indiana",
    abbr: "IN",
    depositCap: "No statutory cap",
    returnDeadlineDays: 45,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can expose the landlord to actual damages plus attorney's fees.",
    statute: "Ind. Code § 32-31-3-12",
  },
  {
    slug: "iowa",
    name: "Iowa",
    abbr: "IA",
    depositCap: "2 months' rent",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in statutory damages up to twice the deposit.",
    statute: "Iowa Code § 562A.12",
  },
  {
    slug: "kansas",
    name: "Kansas",
    abbr: "KS",
    depositCap: "1 month's rent (1.5 months for pet owners)",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Wrongful withholding can allow the tenant to recover the deposit plus damages.",
    statute: "Kan. Stat. § 58-2550",
  },
  {
    slug: "kentucky",
    name: "Kentucky",
    abbr: "KY",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement (in jurisdictions that have adopted the URLTA).",
    separateAccountRequired: true,
    penalty: "Failure to maintain a separate account or itemize deductions can forfeit the right to withhold.",
    statute: "Ky. Rev. Stat. § 383.580",
  },
  {
    slug: "louisiana",
    name: "Louisiana",
    abbr: "LA",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith failure to return can result in damages, plus $200 or actual damages, whichever is greater.",
    statute: "La. Rev. Stat. § 9:3251",
  },
  {
    slug: "maine",
    name: "Maine",
    abbr: "ME",
    depositCap: "2 months' rent",
    returnDeadlineDays: 30,
    returnDeadlineNote: "21 days for tenancy-at-will.",
    interestRequired: false,
    interestNote: "No statewide interest requirement (some exceptions for specific buildings).",
    separateAccountRequired: false,
    penalty: "Wrongful withholding can result in twice the amount owed plus costs.",
    statute: "Me. Rev. Stat. tit. 14, § 6034",
  },
  {
    slug: "maryland",
    name: "Maryland",
    abbr: "MD",
    depositCap: "2 months' rent",
    returnDeadlineDays: 45,
    interestRequired: true,
    interestNote: "Interest is required annually at a rate tied to the U.S. Treasury yield (roughly 1.5%+ depending on year).",
    separateAccountRequired: false,
    penalty: "Bad-faith withholding can result in up to 3x the wrongfully withheld amount.",
    statute: "Md. Code, Real Property § 8-203",
  },
  {
    slug: "massachusetts",
    name: "Massachusetts",
    abbr: "MA",
    depositCap: "1 month's rent",
    returnDeadlineDays: 30,
    interestRequired: true,
    interestNote: "5% annual simple interest (or the rate actually earned in an interest-bearing account) is required.",
    separateAccountRequired: true,
    penalty: "Noncompliance (no separate account, no receipt, no interest) can result in treble damages plus attorney's fees.",
    statute: "Mass. Gen. Laws ch. 186, § 15B",
  },
  {
    slug: "michigan",
    name: "Michigan",
    abbr: "MI",
    depositCap: "1.5 months' rent",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    penalty: "Failure to provide an itemized list within the deadline can forfeit the landlord's right to withhold.",
    statute: "Mich. Comp. Laws § 554.602",
  },
  {
    slug: "minnesota",
    name: "Minnesota",
    abbr: "MN",
    depositCap: "No statutory cap",
    returnDeadlineDays: 21,
    returnDeadlineNote: "3 weeks (21 days) after move-out and delivery of a forwarding address.",
    interestRequired: true,
    interestNote: "Simple annual interest (rate set yearly by the state) is required.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to $500 in punitive damages plus the deposit.",
    statute: "Minn. Stat. § 504B.178",
  },
  {
    slug: "mississippi",
    name: "Mississippi",
    abbr: "MS",
    depositCap: "No statutory cap",
    returnDeadlineDays: 45,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Failure to itemize deductions in writing can forfeit the right to withhold.",
    statute: "Miss. Code § 89-8-21",
  },
  {
    slug: "missouri",
    name: "Missouri",
    abbr: "MO",
    depositCap: "2 months' rent",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Wrongful withholding in bad faith can result in twice the amount wrongfully withheld.",
    statute: "Mo. Rev. Stat. § 535.300",
  },
  {
    slug: "montana",
    name: "Montana",
    abbr: "MT",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    returnDeadlineNote: "10 days if no deductions are claimed, 30 days if deductions are itemized.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to twice the wrongfully withheld amount.",
    statute: "Mont. Code § 70-25-201",
  },
  {
    slug: "nebraska",
    name: "Nebraska",
    abbr: "NE",
    depositCap: "1 month's rent (1.25 months if a pet deposit applies)",
    returnDeadlineDays: 14,
    returnDeadlineNote: "14 days after termination and surrender of the unit.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to twice the amount wrongfully withheld.",
    statute: "Neb. Rev. Stat. § 76-1416",
  },
  {
    slug: "nevada",
    name: "Nevada",
    abbr: "NV",
    depositCap: "3 months' rent",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith withholding can result in damages up to the amount wrongfully withheld.",
    statute: "Nev. Rev. Stat. § 118A.242",
  },
  {
    slug: "new-hampshire",
    name: "New Hampshire",
    abbr: "NH",
    depositCap: "1 month's rent or $100, whichever is greater",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    penalty: "Noncompliance can result in double damages via small claims.",
    statute: "N.H. Rev. Stat. § 540-A:6",
  },
  {
    slug: "new-jersey",
    name: "New Jersey",
    abbr: "NJ",
    depositCap: "1.5 months' rent",
    returnDeadlineDays: 30,
    interestRequired: true,
    interestNote: "Annual interest at the rate paid on a standard savings account is required.",
    separateAccountRequired: true,
    penalty: "Failure to comply can result in double the deposit amount as damages.",
    statute: "N.J. Stat. § 46:8-19",
  },
  {
    slug: "new-mexico",
    name: "New Mexico",
    abbr: "NM",
    depositCap: "1 month's rent for leases under 1 year (no statutory cap for longer leases)",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "Interest is required only on deposits held more than 1 year, at a statutory rate for longer-term leases.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in actual damages plus statutory penalties.",
    statute: "N.M. Stat. § 47-8-18",
  },
  {
    slug: "new-york",
    name: "New York",
    abbr: "NY",
    depositCap: "1 month's rent",
    returnDeadlineDays: 14,
    interestRequired: true,
    interestNote: "Required for buildings with 6 or more units; the deposit must be held in an interest-bearing account.",
    separateAccountRequired: true,
    penalty: "Willful violation of itemization or timing rules can result in forfeiture of the right to withhold and, in bad faith, up to twice the deposit.",
    statute: "N.Y. Gen. Oblig. Law § 7-108",
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    abbr: "NC",
    depositCap: "2 weeks' rent (month-to-month), 1.5 months' rent (lease under 2 years), 2 months' rent (2+ years)",
    returnDeadlineDays: 30,
    returnDeadlineNote: "30 days, extendable to 60 days if the final costs are not yet known.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    penalty: "Failure to comply can result in damages plus court costs and attorney's fees.",
    statute: "N.C. Gen. Stat. § 42-51",
  },
  {
    slug: "north-dakota",
    name: "North Dakota",
    abbr: "ND",
    depositCap: "1 month's rent (may exceed for tenants with pets or poor credit history)",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    penalty: "Bad-faith retention can result in statutory damages up to the deposit amount.",
    statute: "N.D. Cent. Code § 47-16-07.1",
  },
  {
    slug: "ohio",
    name: "Ohio",
    abbr: "OH",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: true,
    interestNote: "5% simple annual interest required only if the deposit exceeds one month's rent and is held over 6 months.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in damages equal to the wrongfully withheld amount, doubled.",
    statute: "Ohio Rev. Code § 5321.16",
  },
  {
    slug: "oklahoma",
    name: "Oklahoma",
    abbr: "OK",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    penalty: "Bad-faith retention can result in up to twice the amount wrongfully withheld.",
    statute: "Okla. Stat. tit. 41, § 115",
  },
  {
    slug: "oregon",
    name: "Oregon",
    abbr: "OR",
    depositCap: "No statutory cap",
    returnDeadlineDays: 31,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to twice the amount wrongfully withheld.",
    statute: "Or. Rev. Stat. § 90.300",
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    abbr: "PA",
    depositCap: "2 months' rent for the first year, 1 month's rent after that",
    returnDeadlineDays: 30,
    interestRequired: true,
    interestNote: "Interest (minus a 1% administrative fee) is required once a deposit has been held for 2+ years.",
    separateAccountRequired: true,
    penalty: "Bad-faith failure to return can result in up to twice the wrongfully withheld amount.",
    statute: "68 Pa. Stat. § 250.512",
  },
  {
    slug: "rhode-island",
    name: "Rhode Island",
    abbr: "RI",
    depositCap: "1 month's rent",
    returnDeadlineDays: 20,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Wrongful withholding can result in up to twice the amount withheld.",
    statute: "R.I. Gen. Laws § 34-18-19",
  },
  {
    slug: "south-carolina",
    name: "South Carolina",
    abbr: "SC",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to 3x the amount wrongfully withheld plus attorney's fees.",
    statute: "S.C. Code § 27-40-410",
  },
  {
    slug: "south-dakota",
    name: "South Dakota",
    abbr: "SD",
    depositCap: "1 month's rent (more allowed if justified by increased risk, e.g., pets)",
    returnDeadlineDays: 14,
    returnDeadlineNote: "2 weeks if no deductions; 45 days if deductions are itemized.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to twice the amount wrongfully withheld.",
    statute: "S.D. Codified Laws § 43-32-24",
  },
  {
    slug: "tennessee",
    name: "Tennessee",
    abbr: "TN",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: true,
    penalty: "Failure to maintain a separate account or account for the deposit can result in the tenant recovering the full amount.",
    statute: "Tenn. Code § 66-28-301",
  },
  {
    slug: "texas",
    name: "Texas",
    abbr: "TX",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in $100 plus 3x the wrongfully withheld portion, plus attorney's fees.",
    statute: "Tex. Prop. Code § 92.109",
  },
  {
    slug: "utah",
    name: "Utah",
    abbr: "UT",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in a penalty of up to $100 per day plus actual damages.",
    statute: "Utah Code § 57-17-3",
  },
  {
    slug: "vermont",
    name: "Vermont",
    abbr: "VT",
    depositCap: "No statutory cap",
    returnDeadlineDays: 14,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Willful noncompliance can result in the tenant recovering the deposit plus damages and attorney's fees.",
    statute: "Vt. Stat. tit. 9, § 4461",
  },
  {
    slug: "virginia",
    name: "Virginia",
    abbr: "VA",
    depositCap: "2 months' rent",
    returnDeadlineDays: 45,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in actual damages plus reasonable attorney's fees.",
    statute: "Va. Code § 55.1-1226",
  },
  {
    slug: "washington",
    name: "Washington",
    abbr: "WA",
    depositCap: "No statutory cap",
    returnDeadlineDays: 21,
    interestRequired: false,
    interestNote: "No statewide interest requirement (Seattle has a separate ordinance).",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to twice the deposit plus attorney's fees.",
    statute: "Wash. Rev. Code § 59.18.280",
  },
  {
    slug: "west-virginia",
    name: "West Virginia",
    abbr: "WV",
    depositCap: "No statutory cap",
    returnDeadlineDays: 60,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Wrongful withholding can result in the tenant recovering actual damages.",
    statute: "W. Va. Code § 37-6A-1",
  },
  {
    slug: "wisconsin",
    name: "Wisconsin",
    abbr: "WI",
    depositCap: "No statutory cap",
    returnDeadlineDays: 21,
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in up to twice the wrongfully withheld amount plus attorney's fees.",
    statute: "Wis. Admin. Code ATCP § 134.06",
  },
  {
    slug: "wyoming",
    name: "Wyoming",
    abbr: "WY",
    depositCap: "No statutory cap",
    returnDeadlineDays: 30,
    returnDeadlineNote: "30 days, or 60 days if the tenant caused damage that requires longer to assess.",
    interestRequired: false,
    interestNote: "No statewide interest requirement.",
    separateAccountRequired: false,
    penalty: "Bad-faith retention can result in the landlord being liable for actual damages.",
    statute: "Wyo. Stat. § 1-21-1208",
  },
];

export function getStateBySlug(slug: string): StateLaw | undefined {
  return statesData.find((s) => s.slug === slug);
}
