import type { Metadata } from "next";
import Link from "next/link";
import { SITE_NAME, CONTACT_EMAIL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Legal Disclaimer",
  description: `${SITE_NAME} provides self-help tools and general information, not legal advice. Read the full disclaimer covering accuracy, generated documents, and your responsibilities.`,
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-14">
      <p className="font-sans text-xs font-bold uppercase tracking-widest text-moss">
        Legal
      </p>
      <h1 className="mt-2 font-serif text-4xl font-bold">Legal Disclaimer</h1>
      <p className="mt-2 font-sans text-sm text-ink/50">
        Last updated:{" "}
        {new Date().toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })}
      </p>

      <div className="mt-8 space-y-6 font-sans text-sm leading-relaxed text-ink/80">
        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Not legal advice
          </h2>
          <p className="mt-2">
            {SITE_NAME} provides self-help calculators, document templates,
            and general summaries of publicly available landlord-tenant law
            for informational purposes only. It is <strong>not</strong> a law
            firm, is not a substitute for an attorney, and does not provide
            legal advice. Using this website, its tools, or its generated
            documents does not create an attorney-client relationship between
            you and {SITE_NAME} or anyone associated with it.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            No guarantee of outcome
          </h2>
          <p className="mt-2">
            Nothing on this site guarantees any particular result — including
            whether a deposit is returned, whether a deduction is upheld, or
            how any dispute, demand, or small-claims matter is resolved. Any
            figures, deadlines, or documents produced are estimates and
            starting points based on the information you enter, not
            determinations of your legal rights or obligations.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Accuracy and currency of information
          </h2>
          <p className="mt-2">
            Landlord-tenant law varies by state and by city, changes over
            time, and can turn on facts specific to your situation. The
            state-by-state summaries, deposit caps, deadlines, interest
            figures, penalties, and statute references on this site are
            general and may be incomplete, out of date, or not applicable to
            your circumstances, and they do not account for local (city or
            county) ordinances that can be stricter. Every effort is made to
            keep them reasonable, but they are provided{" "}
            <strong>&quot;as is&quot; without warranty of any kind</strong>.
            Always verify against the official statute or with a licensed
            attorney before relying on any figure.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Documents you generate
          </h2>
          <p className="mt-2">
            The letters, statements, checklists, receipts, ledgers, and
            packets generated by this site are templates populated with the
            information you provide. You are solely responsible for reviewing
            each document for accuracy and for complying with any notice,
            delivery, timing, or formatting requirements that apply in your
            jurisdiction before you use or send it.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            Limitation of liability
          </h2>
          <p className="mt-2">
            To the fullest extent permitted by law, {SITE_NAME} and its
            operators are not liable for any damages arising from your use of,
            or reliance on, the calculators, templates, documents, or
            information on this site, including damages resulting from errors,
            omissions, or outdated information. Your use of the site is
            governed by our{" "}
            <Link href="/terms" className="underline hover:text-moss">
              Terms of Service
            </Link>
            .
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">
            When to consult a professional
          </h2>
          <p className="mt-2">
            For advice about your specific situation — a contested deposit, an
            eviction, a lease dispute, or anything with meaningful money or
            legal consequences at stake — consult a licensed attorney in your
            state, your local housing authority, or your small-claims court.
            For tax questions, consult a qualified tax professional.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold text-ink">Questions</h2>
          <p className="mt-2">
            Questions about this disclaimer can be sent to{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="underline hover:text-moss">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
